/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Aio;

import Gamelist.Pointblank;
import Gamelist.ML;
import Gamelist.Fortnite;
import Gamelist.Genshin;
import Gamelist.Steam;
import Gamelist.Valorant;
import java.awt.Color;
import java.util.HashSet;

/**
 *
 * @author Fancysx
 */
public class TopupGameList extends javax.swing.JPanel {

    /**
     * Creates new form TopupGameList
     */
    public TopupGameList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Valorant_Card = new roundedpanel.RoundedPanel();
        Innervalo = new javax.swing.JLabel();
        Fortnite_Card = new roundedpanel.RoundedPanel();
        Innerfort = new javax.swing.JLabel();
        ML_Card = new roundedpanel.RoundedPanel();
        Innerml = new javax.swing.JLabel();
        PB_Card = new roundedpanel.RoundedPanel();
        Innerpb = new javax.swing.JLabel();
        Genshin_Card = new roundedpanel.RoundedPanel();
        Innergs = new javax.swing.JLabel();
        STL_Card = new roundedpanel.RoundedPanel();
        InnerSTL = new javax.swing.JLabel();
        Cmstp1 = new roundedpanel.RoundedPanel();
        innercmstp1 = new roundedpanel.RoundedPanel();
        cmstplbl = new javax.swing.JLabel();
        Cmstp2 = new roundedpanel.RoundedPanel();
        innercmstp2 = new roundedpanel.RoundedPanel();
        cmstplbl1 = new javax.swing.JLabel();
        Cmstp3 = new roundedpanel.RoundedPanel();
        innercmstp3 = new roundedpanel.RoundedPanel();
        cmstplbl2 = new javax.swing.JLabel();
        Cmstp4 = new roundedpanel.RoundedPanel();
        innercmstp4 = new roundedpanel.RoundedPanel();
        cmstplbl3 = new javax.swing.JLabel();
        Cmstp5 = new roundedpanel.RoundedPanel();
        innercmstp5 = new roundedpanel.RoundedPanel();
        cmstplbl4 = new javax.swing.JLabel();
        Cmstp6 = new roundedpanel.RoundedPanel();
        innercmstp6 = new roundedpanel.RoundedPanel();
        cmstplbl5 = new javax.swing.JLabel();
        Submenu = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(251, 251, 251));

        Valorant_Card.setBackground(new java.awt.Color(251, 251, 251));
        Valorant_Card.setRoundBottomLeft(25);
        Valorant_Card.setRoundBottomRight(25);
        Valorant_Card.setRoundTopLeft(25);
        Valorant_Card.setRoundTopRight(25);
        Valorant_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Valorant_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Valorant_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Valorant_CardMouseExited(evt);
            }
        });

        Innervalo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/card valo.png"))); // NOI18N
        Innervalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnervaloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnervaloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnervaloMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Valorant_CardLayout = new javax.swing.GroupLayout(Valorant_Card);
        Valorant_Card.setLayout(Valorant_CardLayout);
        Valorant_CardLayout.setHorizontalGroup(
            Valorant_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Valorant_CardLayout.createSequentialGroup()
                .addComponent(Innervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Valorant_CardLayout.setVerticalGroup(
            Valorant_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Innervalo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        Fortnite_Card.setBackground(new java.awt.Color(251, 251, 251));
        Fortnite_Card.setRoundBottomLeft(25);
        Fortnite_Card.setRoundBottomRight(25);
        Fortnite_Card.setRoundTopLeft(25);
        Fortnite_Card.setRoundTopRight(25);
        Fortnite_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fortnite_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Fortnite_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Fortnite_CardMouseExited(evt);
            }
        });

        Innerfort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/card fortnite.png"))); // NOI18N
        Innerfort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnerfortMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnerfortMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnerfortMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Fortnite_CardLayout = new javax.swing.GroupLayout(Fortnite_Card);
        Fortnite_Card.setLayout(Fortnite_CardLayout);
        Fortnite_CardLayout.setHorizontalGroup(
            Fortnite_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fortnite_CardLayout.createSequentialGroup()
                .addComponent(Innerfort, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Fortnite_CardLayout.setVerticalGroup(
            Fortnite_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Innerfort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        ML_Card.setBackground(new java.awt.Color(251, 251, 251));
        ML_Card.setRoundBottomLeft(25);
        ML_Card.setRoundBottomRight(25);
        ML_Card.setRoundTopLeft(25);
        ML_Card.setRoundTopRight(25);
        ML_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ML_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ML_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ML_CardMouseExited(evt);
            }
        });

        Innerml.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Ml card.png"))); // NOI18N
        Innerml.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnermlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnermlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnermlMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ML_CardLayout = new javax.swing.GroupLayout(ML_Card);
        ML_Card.setLayout(ML_CardLayout);
        ML_CardLayout.setHorizontalGroup(
            ML_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ML_CardLayout.createSequentialGroup()
                .addComponent(Innerml, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ML_CardLayout.setVerticalGroup(
            ML_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Innerml, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        PB_Card.setBackground(new java.awt.Color(251, 251, 251));
        PB_Card.setRoundBottomLeft(25);
        PB_Card.setRoundBottomRight(25);
        PB_Card.setRoundTopLeft(25);
        PB_Card.setRoundTopRight(25);
        PB_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PB_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PB_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PB_CardMouseExited(evt);
            }
        });

        Innerpb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/card pb.png"))); // NOI18N
        Innerpb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnerpbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnerpbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnerpbMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PB_CardLayout = new javax.swing.GroupLayout(PB_Card);
        PB_Card.setLayout(PB_CardLayout);
        PB_CardLayout.setHorizontalGroup(
            PB_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PB_CardLayout.createSequentialGroup()
                .addComponent(Innerpb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PB_CardLayout.setVerticalGroup(
            PB_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Innerpb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        Genshin_Card.setBackground(new java.awt.Color(251, 251, 251));
        Genshin_Card.setRoundBottomLeft(25);
        Genshin_Card.setRoundBottomRight(25);
        Genshin_Card.setRoundTopLeft(25);
        Genshin_Card.setRoundTopRight(25);
        Genshin_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Genshin_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Genshin_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Genshin_CardMouseExited(evt);
            }
        });

        Innergs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/card genshin.png"))); // NOI18N
        Innergs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnergsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnergsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnergsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Genshin_CardLayout = new javax.swing.GroupLayout(Genshin_Card);
        Genshin_Card.setLayout(Genshin_CardLayout);
        Genshin_CardLayout.setHorizontalGroup(
            Genshin_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Genshin_CardLayout.createSequentialGroup()
                .addComponent(Innergs, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Genshin_CardLayout.setVerticalGroup(
            Genshin_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Innergs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        STL_Card.setBackground(new java.awt.Color(251, 251, 251));
        STL_Card.setRoundBottomLeft(25);
        STL_Card.setRoundBottomRight(25);
        STL_Card.setRoundTopLeft(25);
        STL_Card.setRoundTopRight(25);
        STL_Card.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STL_CardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STL_CardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STL_CardMouseExited(evt);
            }
        });

        InnerSTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/card steam.png"))); // NOI18N
        InnerSTL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InnerSTLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InnerSTLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InnerSTLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout STL_CardLayout = new javax.swing.GroupLayout(STL_Card);
        STL_Card.setLayout(STL_CardLayout);
        STL_CardLayout.setHorizontalGroup(
            STL_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STL_CardLayout.createSequentialGroup()
                .addComponent(InnerSTL, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        STL_CardLayout.setVerticalGroup(
            STL_CardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InnerSTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        Cmstp1.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp1.setRoundBottomLeft(25);
        Cmstp1.setRoundBottomRight(25);
        Cmstp1.setRoundTopLeft(25);
        Cmstp1.setRoundTopRight(25);
        Cmstp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp1MouseExited(evt);
            }
        });

        innercmstp1.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp1.setRoundBottomLeft(25);
        innercmstp1.setRoundBottomRight(25);
        innercmstp1.setRoundTopLeft(25);
        innercmstp1.setRoundTopRight(25);
        innercmstp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp1MouseExited(evt);
            }
        });

        cmstplbl.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp1Layout = new javax.swing.GroupLayout(innercmstp1);
        innercmstp1.setLayout(innercmstp1Layout);
        innercmstp1Layout.setHorizontalGroup(
            innercmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp1Layout.setVerticalGroup(
            innercmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(cmstplbl)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp1Layout = new javax.swing.GroupLayout(Cmstp1);
        Cmstp1.setLayout(Cmstp1Layout);
        Cmstp1Layout.setHorizontalGroup(
            Cmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp1Layout.setVerticalGroup(
            Cmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Cmstp2.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp2.setRoundBottomLeft(25);
        Cmstp2.setRoundBottomRight(25);
        Cmstp2.setRoundTopLeft(25);
        Cmstp2.setRoundTopRight(25);
        Cmstp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp2MouseExited(evt);
            }
        });

        innercmstp2.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp2.setRoundBottomLeft(25);
        innercmstp2.setRoundBottomRight(25);
        innercmstp2.setRoundTopLeft(25);
        innercmstp2.setRoundTopRight(25);
        innercmstp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp2MouseExited(evt);
            }
        });

        cmstplbl1.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl1.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp2Layout = new javax.swing.GroupLayout(innercmstp2);
        innercmstp2.setLayout(innercmstp2Layout);
        innercmstp2Layout.setHorizontalGroup(
            innercmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp2Layout.setVerticalGroup(
            innercmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cmstplbl1)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp2Layout = new javax.swing.GroupLayout(Cmstp2);
        Cmstp2.setLayout(Cmstp2Layout);
        Cmstp2Layout.setHorizontalGroup(
            Cmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cmstp2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp2Layout.setVerticalGroup(
            Cmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Cmstp3.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp3.setRoundBottomLeft(25);
        Cmstp3.setRoundBottomRight(25);
        Cmstp3.setRoundTopLeft(25);
        Cmstp3.setRoundTopRight(25);
        Cmstp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp3MouseExited(evt);
            }
        });

        innercmstp3.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp3.setRoundBottomLeft(25);
        innercmstp3.setRoundBottomRight(25);
        innercmstp3.setRoundTopLeft(25);
        innercmstp3.setRoundTopRight(25);
        innercmstp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp3MouseExited(evt);
            }
        });

        cmstplbl2.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl2.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp3Layout = new javax.swing.GroupLayout(innercmstp3);
        innercmstp3.setLayout(innercmstp3Layout);
        innercmstp3Layout.setHorizontalGroup(
            innercmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp3Layout.setVerticalGroup(
            innercmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp3Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cmstplbl2)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp3Layout = new javax.swing.GroupLayout(Cmstp3);
        Cmstp3.setLayout(Cmstp3Layout);
        Cmstp3Layout.setHorizontalGroup(
            Cmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cmstp3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp3Layout.setVerticalGroup(
            Cmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Cmstp4.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp4.setRoundBottomLeft(25);
        Cmstp4.setRoundBottomRight(25);
        Cmstp4.setRoundTopLeft(25);
        Cmstp4.setRoundTopRight(25);
        Cmstp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp4MouseExited(evt);
            }
        });

        innercmstp4.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp4.setRoundBottomLeft(25);
        innercmstp4.setRoundBottomRight(25);
        innercmstp4.setRoundTopLeft(25);
        innercmstp4.setRoundTopRight(25);
        innercmstp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp4MouseExited(evt);
            }
        });

        cmstplbl3.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl3.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp4Layout = new javax.swing.GroupLayout(innercmstp4);
        innercmstp4.setLayout(innercmstp4Layout);
        innercmstp4Layout.setHorizontalGroup(
            innercmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp4Layout.setVerticalGroup(
            innercmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp4Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cmstplbl3)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp4Layout = new javax.swing.GroupLayout(Cmstp4);
        Cmstp4.setLayout(Cmstp4Layout);
        Cmstp4Layout.setHorizontalGroup(
            Cmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cmstp4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp4Layout.setVerticalGroup(
            Cmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Cmstp5.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp5.setRoundBottomLeft(25);
        Cmstp5.setRoundBottomRight(25);
        Cmstp5.setRoundTopLeft(25);
        Cmstp5.setRoundTopRight(25);
        Cmstp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp5MouseExited(evt);
            }
        });

        innercmstp5.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp5.setRoundBottomLeft(25);
        innercmstp5.setRoundBottomRight(25);
        innercmstp5.setRoundTopLeft(25);
        innercmstp5.setRoundTopRight(25);
        innercmstp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp5MouseExited(evt);
            }
        });

        cmstplbl4.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl4.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp5Layout = new javax.swing.GroupLayout(innercmstp5);
        innercmstp5.setLayout(innercmstp5Layout);
        innercmstp5Layout.setHorizontalGroup(
            innercmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp5Layout.setVerticalGroup(
            innercmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp5Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cmstplbl4)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp5Layout = new javax.swing.GroupLayout(Cmstp5);
        Cmstp5.setLayout(Cmstp5Layout);
        Cmstp5Layout.setHorizontalGroup(
            Cmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cmstp5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp5Layout.setVerticalGroup(
            Cmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Cmstp6.setBackground(new java.awt.Color(27, 34, 45));
        Cmstp6.setRoundBottomLeft(25);
        Cmstp6.setRoundBottomRight(25);
        Cmstp6.setRoundTopLeft(25);
        Cmstp6.setRoundTopRight(25);
        Cmstp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cmstp6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Cmstp6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Cmstp6MouseExited(evt);
            }
        });

        innercmstp6.setBackground(new java.awt.Color(255, 255, 255));
        innercmstp6.setRoundBottomLeft(25);
        innercmstp6.setRoundBottomRight(25);
        innercmstp6.setRoundTopLeft(25);
        innercmstp6.setRoundTopRight(25);
        innercmstp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                innercmstp6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                innercmstp6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                innercmstp6MouseExited(evt);
            }
        });

        cmstplbl5.setFont(new java.awt.Font("VALORANT", 1, 12)); // NOI18N
        cmstplbl5.setText("COMING SOON");

        javax.swing.GroupLayout innercmstp6Layout = new javax.swing.GroupLayout(innercmstp6);
        innercmstp6.setLayout(innercmstp6Layout);
        innercmstp6Layout.setHorizontalGroup(
            innercmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innercmstp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmstplbl5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        innercmstp6Layout.setVerticalGroup(
            innercmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innercmstp6Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(cmstplbl5)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout Cmstp6Layout = new javax.swing.GroupLayout(Cmstp6);
        Cmstp6.setLayout(Cmstp6Layout);
        Cmstp6Layout.setHorizontalGroup(
            Cmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
            .addGroup(Cmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Cmstp6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Cmstp6Layout.setVerticalGroup(
            Cmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(Cmstp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cmstp6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(innercmstp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        Submenu.setBackground(new java.awt.Color(153, 153, 153));
        Submenu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Submenu.setForeground(new java.awt.Color(27, 34, 45));
        Submenu.setText("Product> Top-Up Games");
        Submenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmenuMouseExited(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Game Controller.png"))); // NOI18N

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Submenu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Valorant_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Fortnite_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ML_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(PB_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(Genshin_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(STL_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Cmstp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Cmstp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Cmstp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Cmstp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Cmstp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Cmstp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Submenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valorant_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fortnite_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ML_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PB_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Genshin_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(STL_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cmstp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmstp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmstp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmstp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmstp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cmstp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void Valorant_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Valorant_CardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Valorant_CardMouseExited

    private void Valorant_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Valorant_CardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Valorant_CardMouseEntered

    private void Valorant_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Valorant_CardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Valorant_CardMouseClicked

    private void InnervaloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnervaloMouseEntered
        Valorant_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnervaloMouseEntered

    private void InnervaloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnervaloMouseExited
        Valorant_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnervaloMouseExited

    private void InnervaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnervaloMouseClicked
        Valorant_Card.setBackground(new Color(232,232,232));
        new Valorant().setVisible(true);
    }//GEN-LAST:event_InnervaloMouseClicked

    private void InnerfortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerfortMouseClicked
        Fortnite_Card.setBackground(new Color(232,232,232));
        new Fortnite().setVisible(true);
    }//GEN-LAST:event_InnerfortMouseClicked

    private void InnerfortMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerfortMouseEntered
        Fortnite_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnerfortMouseEntered

    private void InnerfortMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerfortMouseExited
        Fortnite_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnerfortMouseExited

    private void Fortnite_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fortnite_CardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Fortnite_CardMouseClicked

    private void Fortnite_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fortnite_CardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Fortnite_CardMouseEntered

    private void Fortnite_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fortnite_CardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Fortnite_CardMouseExited

    private void InnermlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnermlMouseClicked
        new ML().setVisible(true);
    }//GEN-LAST:event_InnermlMouseClicked

    private void InnermlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnermlMouseEntered
        ML_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnermlMouseEntered

    private void InnermlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnermlMouseExited
        ML_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnermlMouseExited

    private void ML_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ML_CardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ML_CardMouseClicked

    private void ML_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ML_CardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ML_CardMouseEntered

    private void ML_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ML_CardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ML_CardMouseExited

    private void InnerpbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerpbMouseClicked
        PB_Card.setBackground(new Color(232,232,232));
        new Pointblank().setVisible(true);
    }//GEN-LAST:event_InnerpbMouseClicked

    private void InnerpbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerpbMouseEntered
        PB_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnerpbMouseEntered

    private void InnerpbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerpbMouseExited
        PB_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnerpbMouseExited

    private void PB_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB_CardMouseClicked
       
    }//GEN-LAST:event_PB_CardMouseClicked

    private void PB_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB_CardMouseEntered
        
    }//GEN-LAST:event_PB_CardMouseEntered

    private void PB_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PB_CardMouseExited
        
    }//GEN-LAST:event_PB_CardMouseExited

    private void InnergsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnergsMouseClicked
        Genshin_Card.setBackground(new Color(232,232,232));
        new Genshin().setVisible(true);
    }//GEN-LAST:event_InnergsMouseClicked

    private void InnergsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnergsMouseEntered
        Genshin_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnergsMouseEntered

    private void InnergsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnergsMouseExited
        Genshin_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnergsMouseExited

    private void Genshin_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Genshin_CardMouseClicked
        
    }//GEN-LAST:event_Genshin_CardMouseClicked

    private void Genshin_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Genshin_CardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Genshin_CardMouseEntered

    private void Genshin_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Genshin_CardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Genshin_CardMouseExited

    private void InnerSTLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerSTLMouseClicked
        STL_Card.setBackground(new Color(232,232,232));
        new Steam().setVisible(true);
    }//GEN-LAST:event_InnerSTLMouseClicked

    private void InnerSTLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerSTLMouseEntered
        STL_Card.setBackground(new Color(232,232,232));
    }//GEN-LAST:event_InnerSTLMouseEntered

    private void InnerSTLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InnerSTLMouseExited
        STL_Card.setBackground(new Color(251,251,251));
    }//GEN-LAST:event_InnerSTLMouseExited

    private void STL_CardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STL_CardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_STL_CardMouseClicked

    private void STL_CardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STL_CardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_STL_CardMouseEntered

    private void STL_CardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STL_CardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_STL_CardMouseExited

    private void Cmstp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp1MouseClicked

    private void Cmstp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp1MouseEntered

    private void Cmstp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp1MouseExited

    private void innercmstp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp1MouseClicked

    private void innercmstp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp1MouseEntered

    private void innercmstp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp1MouseExited

    private void innercmstp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp2MouseClicked

    private void innercmstp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp2MouseEntered

    private void innercmstp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp2MouseExited

    private void Cmstp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp2MouseClicked

    private void Cmstp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp2MouseEntered

    private void Cmstp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp2MouseExited

    private void innercmstp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp3MouseClicked

    private void innercmstp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp3MouseEntered

    private void innercmstp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp3MouseExited

    private void Cmstp3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp3MouseClicked

    private void Cmstp3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp3MouseEntered

    private void Cmstp3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp3MouseExited

    private void innercmstp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp4MouseClicked

    private void innercmstp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp4MouseEntered

    private void innercmstp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp4MouseExited

    private void Cmstp4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp4MouseClicked

    private void Cmstp4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp4MouseEntered

    private void Cmstp4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp4MouseExited

    private void innercmstp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp5MouseClicked

    private void innercmstp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp5MouseEntered

    private void innercmstp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp5MouseExited

    private void Cmstp5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp5MouseClicked

    private void Cmstp5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp5MouseEntered

    private void Cmstp5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp5MouseExited

    private void innercmstp6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp6MouseClicked

    private void innercmstp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp6MouseEntered

    private void innercmstp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_innercmstp6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_innercmstp6MouseExited

    private void Cmstp6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp6MouseClicked

    private void Cmstp6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp6MouseEntered

    private void Cmstp6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cmstp6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmstp6MouseExited

    private void SubmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmenuMouseClicked
        setVisible(false);
    }//GEN-LAST:event_SubmenuMouseClicked

    private void SubmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmenuMouseEntered
        String s = "<HTML><u>Product> Top-Up Games</u></HTML>";
        Submenu.setText(s);
    }//GEN-LAST:event_SubmenuMouseEntered

    private void SubmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmenuMouseExited
        String s = "Product> Top-Up Games";
        Submenu.setText(s);
    }//GEN-LAST:event_SubmenuMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private roundedpanel.RoundedPanel Cmstp1;
    private roundedpanel.RoundedPanel Cmstp2;
    private roundedpanel.RoundedPanel Cmstp3;
    private roundedpanel.RoundedPanel Cmstp4;
    private roundedpanel.RoundedPanel Cmstp5;
    private roundedpanel.RoundedPanel Cmstp6;
    private roundedpanel.RoundedPanel Fortnite_Card;
    private roundedpanel.RoundedPanel Genshin_Card;
    private javax.swing.JLabel InnerSTL;
    private javax.swing.JLabel Innerfort;
    private javax.swing.JLabel Innergs;
    private javax.swing.JLabel Innerml;
    private javax.swing.JLabel Innerpb;
    private javax.swing.JLabel Innervalo;
    private roundedpanel.RoundedPanel ML_Card;
    private roundedpanel.RoundedPanel PB_Card;
    private javax.swing.JPanel Panel;
    private roundedpanel.RoundedPanel STL_Card;
    private javax.swing.JLabel Submenu;
    private roundedpanel.RoundedPanel Valorant_Card;
    private javax.swing.JLabel cmstplbl;
    private javax.swing.JLabel cmstplbl1;
    private javax.swing.JLabel cmstplbl2;
    private javax.swing.JLabel cmstplbl3;
    private javax.swing.JLabel cmstplbl4;
    private javax.swing.JLabel cmstplbl5;
    private javax.swing.JLabel icon;
    private roundedpanel.RoundedPanel innercmstp1;
    private roundedpanel.RoundedPanel innercmstp2;
    private roundedpanel.RoundedPanel innercmstp3;
    private roundedpanel.RoundedPanel innercmstp4;
    private roundedpanel.RoundedPanel innercmstp5;
    private roundedpanel.RoundedPanel innercmstp6;
    // End of variables declaration//GEN-END:variables
}


