/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gamelist;
import BillingManagementSys.Dashboard;
import java.awt.Color;
import DBConfig.ConnectDb;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fancysx
 */
public class Fortnite extends javax.swing.JFrame {
    public Connection conn;
    public Fortnite() {
        initComponents();
        setTitle("Valorant");
        conn = ConnectDb.getConnection();
    }

     
        
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttongroupvp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Riot_Data = new roundedpanel.RoundedPanel();
        Number2 = new roundedpanel.RoundedPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        roundedPanel3 = new roundedpanel.RoundedPanel();
        UID = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Submenu = new javax.swing.JLabel();
        Qty_Item = new roundedpanel.RoundedPanel();
        Number = new roundedpanel.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nominal1 = new roundedpanel.RoundedPanel();
        Vb2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Nominal4 = new roundedpanel.RoundedPanel();
        Vb4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Nominal2 = new roundedpanel.RoundedPanel();
        Vb3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Nominal3 = new roundedpanel.RoundedPanel();
        Vb6 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Nominal5 = new roundedpanel.RoundedPanel();
        Vb1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Nominal6 = new roundedpanel.RoundedPanel();
        Vb5 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Metode_Pembayaran = new roundedpanel.RoundedPanel();
        Number3 = new roundedpanel.RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        Methodbayar = new javax.swing.JComboBox<>();
        No_WhasApp = new roundedpanel.RoundedPanel();
        Number1 = new roundedpanel.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        roundedPanel4 = new roundedpanel.RoundedPanel();
        Contact = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnPesan = new roundedpanel.RoundedPanel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 0));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 34, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Riot_Data.setBackground(new java.awt.Color(61, 61, 79));
        Riot_Data.setRoundBottomLeft(25);
        Riot_Data.setRoundBottomRight(25);
        Riot_Data.setRoundTopLeft(25);
        Riot_Data.setRoundTopRight(25);

        Number2.setBackground(new java.awt.Color(211, 118, 31));
        Number2.setRoundTopLeft(25);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("1");

        javax.swing.GroupLayout Number2Layout = new javax.swing.GroupLayout(Number2);
        Number2.setLayout(Number2Layout);
        Number2Layout.setHorizontalGroup(
            Number2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Number2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel23)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Number2Layout.setVerticalGroup(
            Number2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Number2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Masukkan Data Akun Anda");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Username Fortnite");

        roundedPanel3.setBackground(new java.awt.Color(214, 214, 225));
        roundedPanel3.setRoundBottomLeft(15);
        roundedPanel3.setRoundBottomRight(15);
        roundedPanel3.setRoundTopLeft(15);
        roundedPanel3.setRoundTopRight(15);

        UID.setBackground(new java.awt.Color(214, 214, 225));
        UID.setBorder(null);
        UID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UID, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UID)
                .addContainerGap())
        );

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Untuk menemukan Username Anda, buka halaman profil epic games dan salin menggunakan");

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("tombol yang tersedia (Contoh: VxkEPIC2911 )");

        Submenu.setBackground(new java.awt.Color(255, 255, 255));
        Submenu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Submenu.setForeground(new java.awt.Color(255, 255, 255));
        Submenu.setText("Product > Top-Up Games");
        Submenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Riot_DataLayout = new javax.swing.GroupLayout(Riot_Data);
        Riot_Data.setLayout(Riot_DataLayout);
        Riot_DataLayout.setHorizontalGroup(
            Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(Riot_DataLayout.createSequentialGroup()
                .addGroup(Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Riot_DataLayout.createSequentialGroup()
                        .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(Submenu))
                    .addGroup(Riot_DataLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Riot_DataLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Riot_DataLayout.setVerticalGroup(
            Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Riot_DataLayout.createSequentialGroup()
                .addGroup(Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Number2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Riot_DataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Riot_DataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Submenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel26)
                .addGap(1, 1, 1)
                .addComponent(jLabel27)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(Riot_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 590, 200));

        Qty_Item.setBackground(new java.awt.Color(61, 61, 79));
        Qty_Item.setRoundBottomLeft(25);
        Qty_Item.setRoundBottomRight(25);
        Qty_Item.setRoundTopLeft(25);
        Qty_Item.setRoundTopRight(25);

        Number.setBackground(new java.awt.Color(211, 118, 31));
        Number.setRoundTopLeft(25);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("2");

        javax.swing.GroupLayout NumberLayout = new javax.swing.GroupLayout(Number);
        Number.setLayout(NumberLayout);
        NumberLayout.setHorizontalGroup(
            NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NumberLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        NumberLayout.setVerticalGroup(
            NumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NumberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pilih Nominal Yang Ingin Anda Beli");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Diamond");

        Nominal1.setBackground(new java.awt.Color(214, 214, 225));
        Nominal1.setRoundBottomLeft(15);
        Nominal1.setRoundBottomRight(15);
        Nominal1.setRoundTopLeft(15);
        Nominal1.setRoundTopRight(15);

        Vb2.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb2);
        Vb2.setText("2800 V-Bucks");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("Rp. 430.159");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal1Layout = new javax.swing.GroupLayout(Nominal1);
        Nominal1.setLayout(Nominal1Layout);
        Nominal1Layout.setHorizontalGroup(
            Nominal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal1Layout.createSequentialGroup()
                .addGroup(Nominal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nominal1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Nominal1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Vb2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(23, 23, 23))
        );
        Nominal1Layout.setVerticalGroup(
            Nominal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Nominal1Layout.createSequentialGroup()
                        .addComponent(Vb2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Nominal4.setBackground(new java.awt.Color(214, 214, 225));
        Nominal4.setRoundBottomLeft(15);
        Nominal4.setRoundBottomRight(15);
        Nominal4.setRoundTopLeft(15);
        Nominal4.setRoundTopRight(15);

        Vb4.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb4);
        Vb4.setText("13500  V-Bucks");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel17.setText("Rp. 1.648.297");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal4Layout = new javax.swing.GroupLayout(Nominal4);
        Nominal4.setLayout(Nominal4Layout);
        Nominal4Layout.setHorizontalGroup(
            Nominal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Nominal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vb4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Nominal4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(23, 23, 23))
        );
        Nominal4Layout.setVerticalGroup(
            Nominal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Nominal4Layout.createSequentialGroup()
                        .addComponent(Vb4)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Nominal2.setBackground(new java.awt.Color(214, 214, 225));
        Nominal2.setRoundBottomLeft(15);
        Nominal2.setRoundBottomRight(15);
        Nominal2.setRoundTopLeft(15);
        Nominal2.setRoundTopRight(15);

        Vb3.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb3);
        Vb3.setText("5000  V-Bucks");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("Rp. 690.901");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal2Layout = new javax.swing.GroupLayout(Nominal2);
        Nominal2.setLayout(Nominal2Layout);
        Nominal2Layout.setHorizontalGroup(
            Nominal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Nominal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nominal2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Vb3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(23, 23, 23))
        );
        Nominal2Layout.setVerticalGroup(
            Nominal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Nominal2Layout.createSequentialGroup()
                        .addComponent(Vb3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Nominal3.setBackground(new java.awt.Color(214, 214, 225));
        Nominal3.setRoundBottomLeft(15);
        Nominal3.setRoundBottomRight(15);
        Nominal3.setRoundTopLeft(15);
        Nominal3.setRoundTopRight(15);

        Vb6.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb6);
        Vb6.setText("4350  V-Bucks");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("Rp. 4.721.376");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal3Layout = new javax.swing.GroupLayout(Nominal3);
        Nominal3.setLayout(Nominal3Layout);
        Nominal3Layout.setHorizontalGroup(
            Nominal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Nominal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nominal3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Vb6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(23, 23, 23))
        );
        Nominal3Layout.setVerticalGroup(
            Nominal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Nominal3Layout.createSequentialGroup()
                        .addComponent(Vb6)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel15)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Nominal5.setBackground(new java.awt.Color(214, 214, 225));
        Nominal5.setRoundBottomLeft(15);
        Nominal5.setRoundBottomRight(15);
        Nominal5.setRoundTopLeft(15);
        Nominal5.setRoundTopRight(15);

        Vb1.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb1);
        Vb1.setText("1000 V-Bucks");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel19.setText("Rp. 185.823");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal5Layout = new javax.swing.GroupLayout(Nominal5);
        Nominal5.setLayout(Nominal5Layout);
        Nominal5Layout.setHorizontalGroup(
            Nominal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Nominal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nominal5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Vb1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(23, 23, 23))
        );
        Nominal5Layout.setVerticalGroup(
            Nominal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Nominal5Layout.createSequentialGroup()
                        .addComponent(Vb1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel19)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Nominal6.setBackground(new java.awt.Color(214, 214, 225));
        Nominal6.setRoundBottomLeft(15);
        Nominal6.setRoundBottomRight(15);
        Nominal6.setRoundTopLeft(15);
        Nominal6.setRoundTopRight(15);

        Vb5.setBackground(new java.awt.Color(214, 214, 225));
        buttongroupvp.add(Vb5);
        Vb5.setText("2800  V-Bucks");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel21.setText("Rp 2.739.941");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/VBUCKS.png"))); // NOI18N

        javax.swing.GroupLayout Nominal6Layout = new javax.swing.GroupLayout(Nominal6);
        Nominal6.setLayout(Nominal6Layout);
        Nominal6Layout.setHorizontalGroup(
            Nominal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Nominal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Nominal6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Vb5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(23, 23, 23))
        );
        Nominal6Layout.setVerticalGroup(
            Nominal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Nominal6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Nominal6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Nominal6Layout.createSequentialGroup()
                        .addComponent(Vb5)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel21)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Qty_ItemLayout = new javax.swing.GroupLayout(Qty_Item);
        Qty_Item.setLayout(Qty_ItemLayout);
        Qty_ItemLayout.setHorizontalGroup(
            Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(Qty_ItemLayout.createSequentialGroup()
                .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Qty_ItemLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Qty_ItemLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Qty_ItemLayout.createSequentialGroup()
                        .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Qty_ItemLayout.createSequentialGroup()
                                .addComponent(Nominal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(Nominal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Qty_ItemLayout.createSequentialGroup()
                                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nominal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nominal6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Qty_ItemLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(Nominal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Qty_ItemLayout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(Nominal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(42, 42, 42))))
        );
        Qty_ItemLayout.setVerticalGroup(
            Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Qty_ItemLayout.createSequentialGroup()
                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Qty_ItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nominal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nominal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Nominal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nominal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Qty_ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nominal6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nominal3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(Qty_Item, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 590, 390));

        Metode_Pembayaran.setBackground(new java.awt.Color(61, 61, 79));
        Metode_Pembayaran.setRoundBottomLeft(25);
        Metode_Pembayaran.setRoundBottomRight(25);
        Metode_Pembayaran.setRoundTopLeft(25);
        Metode_Pembayaran.setRoundTopRight(25);

        Number3.setBackground(new java.awt.Color(211, 118, 31));
        Number3.setRoundTopLeft(25);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3");

        javax.swing.GroupLayout Number3Layout = new javax.swing.GroupLayout(Number3);
        Number3.setLayout(Number3Layout);
        Number3Layout.setHorizontalGroup(
            Number3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Number3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Number3Layout.setVerticalGroup(
            Number3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Number3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pilih Metode Pembayaran");

        Methodbayar.setBackground(new java.awt.Color(214, 214, 225));
        Methodbayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih Metode Pembayaran", "Qris (Admin + 1000)", "Shoppe Pay (Admin + 2500)", "Gopay (Admin + 2500)", "BCA VA (Admin + 5500)", "BRI VA (Admin + 2500)", "MANDIRI VA (Admin + 4500)" }));
        Methodbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodbayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Metode_PembayaranLayout = new javax.swing.GroupLayout(Metode_Pembayaran);
        Metode_Pembayaran.setLayout(Metode_PembayaranLayout);
        Metode_PembayaranLayout.setHorizontalGroup(
            Metode_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(Metode_PembayaranLayout.createSequentialGroup()
                .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Metode_PembayaranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Methodbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        Metode_PembayaranLayout.setVerticalGroup(
            Metode_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Metode_PembayaranLayout.createSequentialGroup()
                .addGroup(Metode_PembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Number3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Metode_PembayaranLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Methodbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(Metode_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 590, 130));

        No_WhasApp.setBackground(new java.awt.Color(61, 61, 79));
        No_WhasApp.setRoundBottomLeft(25);
        No_WhasApp.setRoundBottomRight(25);
        No_WhasApp.setRoundTopLeft(25);
        No_WhasApp.setRoundTopRight(25);

        Number1.setBackground(new java.awt.Color(211, 118, 31));
        Number1.setRoundTopLeft(25);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4");

        javax.swing.GroupLayout Number1Layout = new javax.swing.GroupLayout(Number1);
        Number1.setLayout(Number1Layout);
        Number1Layout.setHorizontalGroup(
            Number1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Number1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Number1Layout.setVerticalGroup(
            Number1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Number1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. WhatsApp");

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("No. WhatsApp");

        roundedPanel4.setBackground(new java.awt.Color(214, 214, 225));
        roundedPanel4.setRoundBottomLeft(15);
        roundedPanel4.setRoundBottomRight(15);
        roundedPanel4.setRoundTopLeft(15);
        roundedPanel4.setRoundTopRight(15);

        Contact.setBackground(new java.awt.Color(214, 214, 225));
        Contact.setBorder(null);
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contact, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Contact)
                .addContainerGap())
        );

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Nomor ini akan dihubungi jika ada masalah");

        javax.swing.GroupLayout No_WhasAppLayout = new javax.swing.GroupLayout(No_WhasApp);
        No_WhasApp.setLayout(No_WhasAppLayout);
        No_WhasAppLayout.setHorizontalGroup(
            No_WhasAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(No_WhasAppLayout.createSequentialGroup()
                .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, No_WhasAppLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(No_WhasAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(24, 24, 24))
        );
        No_WhasAppLayout.setVerticalGroup(
            No_WhasAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No_WhasAppLayout.createSequentialGroup()
                .addGroup(No_WhasAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Number1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(No_WhasAppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel1.add(No_WhasApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 800, 590, 170));

        btnPesan.setBackground(new java.awt.Color(211, 118, 31));
        btnPesan.setRoundBottomLeft(15);
        btnPesan.setRoundBottomRight(15);
        btnPesan.setRoundTopLeft(15);
        btnPesan.setRoundTopRight(15);
        btnPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesanMouseClicked(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Pesan sekarang.png"))); // NOI18N
        jLabel30.setText("PESAN SEKARANG");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel30MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel30MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPesanLayout = new javax.swing.GroupLayout(btnPesan);
        btnPesan.setLayout(btnPesanLayout);
        btnPesanLayout.setHorizontalGroup(
            btnPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(btnPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPesanLayout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
        );
        btnPesanLayout.setVerticalGroup(
            btnPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
            .addGroup(btnPesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnPesanLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        jPanel1.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 990, 590, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UIDActionPerformed

    private void MethodbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MethodbayarActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void SubmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmenuMouseClicked
        setVisible(false);
    }//GEN-LAST:event_SubmenuMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        btnPesan.setBackground(new Color(184,115,50));
        try {
            String query;
            Statement st = conn.createStatement();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
            String Date = dateFormat.format(new Date());
            String Time = timeFormat.format(new Date());
            if ("".equals(UID.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "EPIC ID is required", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("".equals(Contact.getText())) {
                JOptionPane.showMessageDialog(new JFrame(), "Contact Number is required!!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (buttongroupvp.getSelection() == null) {
                JOptionPane.showMessageDialog(this, "Anda belum memilih jumlah Valorant Point, pilih terlebih dahulu", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if ("Pilih Metode Pembayaran".equals(Methodbayar.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Anda belum memilih metode pembayaran, pilih metode pembayaran terlebih dahulu", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                int jawab = JOptionPane.showConfirmDialog(null, "Pastikan Data Customer sudah benar, ingin melanjutkan?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (jawab == 0) {
                    String uid = UID.getText();
                    String contact = Contact.getText();
                    String method = (String) Methodbayar.getSelectedItem();
                    int price = 0;
                    int admin = 0;

                    String Vbucks;
                    if(Vb1.isSelected()){
                        Vbucks=Vb1.getText();
                        price = 185823;
                    }else if(Vb2.isSelected()){
                        Vbucks=Vb2.getText();
                        price = 430159;
                    }else if(Vb4.isSelected()){
                        Vbucks=Vb4.getText();
                        price = 1648297;
                    }else if(Vb3.isSelected()){
                        Vbucks=Vb3.getText();
                        price = 690901;
                    }else if(Vb5.isSelected()){
                        Vbucks=Vb5.getText();
                        price = 2739941;
                    }else if(Vb6.isSelected()){
                        Vbucks=Vb6.getText();
                        price = 4721376;
                    }else{
                        Vbucks="";
                    }

                    switch(method){
                        case "Qris (Admin + 1000)":
                        admin = 1000;
                        break;
                        case "Shoppe Pay (Admin + 2500)":
                        admin = 2500;
                        break;
                        case "Gopay (Admin + 2500)":
                        admin = 2500;
                        break;
                        case "BCA VA (Admin + 5500)":
                        admin = 5500;
                        break;
                        case "BRI VA (Admin + 2500)":
                        admin = 2500;
                        break;
                        case "MANDIRI VA (Admin + 4500)":
                        admin = 4500;
                        break;
                    }

                    double total = price + admin;

                    query = "INSERT INTO topupgames(UID, Nominal, Price, Payment, Contact, Total, Date, Time)"+
                    "VALUES('"+uid+"', '"+Vbucks+"', 'Rp. "+price+"','"+method+"' , '"+contact+"', 'Rp. "+total+"', '"+Date+"', '"+Time+"')";

                    st.execute(query);

                    String path = "D:\\Vxknet\\Invoice TopupGame\\Fortnite\\";
                    com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
                    try {
                        PdfWriter.getInstance(doc, new FileOutputStream(path + "" + uid + " " + ".pdf"));
                        doc.open();
                        Paragraph paragraph1 = new Paragraph("                                                                 VxKNET  (Invoice)\n                               Tempat Top-UP game Termurah, Tercepat, dan Terpercaya!!!\n                                                    Contact Number: (+62) 81390545873\n\n\n\n");
                        doc.add(paragraph1);

                        Paragraph paragraph2 = new Paragraph("Date   :  "+Date+"\nTime   : "+Time+"\n\n\n");
                        doc.add(paragraph2);

                        Paragraph paragraph3 = new Paragraph("UID                        :   "+uid+"\nNominal                 :   "+Vbucks+"\nPrice                      :   Rp. "+price+"\nPaymen Method    :   "+method+"\nContact                  :   "+contact+"\nTotal                      :   Rp. "+total+"\n\n\n\n");
                        doc.add(paragraph3);

                        Paragraph paragraph4 = new Paragraph("Thank you for Buying>_!\nVxKNET. ");
                        doc.add(paragraph4);
                        System.out.print("Bill generated");

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    } finally {
                        doc.close();
                    }
                    UID.setText("");
                    buttongroupvp.clearSelection();
                    Contact.setText("");
                    Methodbayar.setSelectedItem("Silahkan Pilih Metode Pembayaran");
                    JOptionPane.showMessageDialog(new JFrame(), "Top-Up Vbucks Fortnite Succes! Silahkan tunggu 1-5 menit dan cek akun anda :) ", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (Exception e) {
            System.out.println("ERROR! " + e.getMessage());
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel30MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseEntered
        btnPesan.setBackground(new Color(237,139,48));
    }//GEN-LAST:event_jLabel30MouseEntered

    private void jLabel30MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseExited
        btnPesan.setBackground(new Color(211,118,31));
    }//GEN-LAST:event_jLabel30MouseExited

    private void btnPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesanMouseClicked
       
    }//GEN-LAST:event_btnPesanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fortnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fortnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fortnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fortnite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fortnite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contact;
    private javax.swing.JComboBox<String> Methodbayar;
    private roundedpanel.RoundedPanel Metode_Pembayaran;
    private roundedpanel.RoundedPanel No_WhasApp;
    private roundedpanel.RoundedPanel Nominal1;
    private roundedpanel.RoundedPanel Nominal2;
    private roundedpanel.RoundedPanel Nominal3;
    private roundedpanel.RoundedPanel Nominal4;
    private roundedpanel.RoundedPanel Nominal5;
    private roundedpanel.RoundedPanel Nominal6;
    private roundedpanel.RoundedPanel Number;
    private roundedpanel.RoundedPanel Number1;
    private roundedpanel.RoundedPanel Number2;
    private roundedpanel.RoundedPanel Number3;
    private roundedpanel.RoundedPanel Qty_Item;
    private roundedpanel.RoundedPanel Riot_Data;
    private javax.swing.JLabel Submenu;
    private javax.swing.JTextField UID;
    private javax.swing.JRadioButton Vb1;
    private javax.swing.JRadioButton Vb2;
    private javax.swing.JRadioButton Vb3;
    private javax.swing.JRadioButton Vb4;
    private javax.swing.JRadioButton Vb5;
    private javax.swing.JRadioButton Vb6;
    private roundedpanel.RoundedPanel btnPesan;
    private javax.swing.ButtonGroup buttongroupvp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private roundedpanel.RoundedPanel roundedPanel3;
    private roundedpanel.RoundedPanel roundedPanel4;
    // End of variables declaration//GEN-END:variables
}
