/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BillingManagementSys;

import Aio.Administrator_List;
import Aio.Find_Member;
import Aio.FoodandDrink;
import Aio.History_Transaction;
import Aio.History_Transaction_Topupgame;
import Aio.Member_List;
import Aio.Member_List_ownerdash;
import Aio.New_Member;
import Aio.New_Product;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fancysx
 */
public class Dashboardowner extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboardowner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alterlayer = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Billing_system3 = new javax.swing.JLabel();
        Billing_system1 = new javax.swing.JLabel();
        Billing_system2 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Master = new javax.swing.JLabel();
        Details_administrator = new javax.swing.JPanel();
        animate_show2 = new javax.swing.JPanel();
        icon_detailsmember = new javax.swing.JLabel();
        List_administrator = new javax.swing.JLabel();
        New_product = new javax.swing.JPanel();
        animate_show3 = new javax.swing.JPanel();
        icon_detailsmember1 = new javax.swing.JLabel();
        Add_product = new javax.swing.JLabel();
        TopupGame = new javax.swing.JPanel();
        animate_show4 = new javax.swing.JPanel();
        icon_topupgame = new javax.swing.JLabel();
        Topup_Game = new javax.swing.JLabel();
        FoodandDrink = new javax.swing.JPanel();
        animate_show6 = new javax.swing.JPanel();
        icon_topupgame1 = new javax.swing.JLabel();
        Food_Drink = new javax.swing.JLabel();
        Details_member = new javax.swing.JPanel();
        animate_show5 = new javax.swing.JPanel();
        icon_detailsmember2 = new javax.swing.JLabel();
        List_member = new javax.swing.JLabel();
        Transaction_History = new javax.swing.JPanel();
        animate_show9 = new javax.swing.JPanel();
        icon_transactionhistory = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        Mainbar = new javax.swing.JPanel();
        forshow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Alterlayer.setBackground(new java.awt.Color(251, 251, 251));
        Alterlayer.setName(""); // NOI18N
        Alterlayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left.setBackground(new java.awt.Color(255, 255, 255));

        Billing_system3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Billing_system3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Battle.net.png"))); // NOI18N

        Billing_system1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Billing_system1.setText("VxK");

        Billing_system2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Billing_system2.setText("NET™");

        Logout.setBackground(new java.awt.Color(27, 34, 45));
        Logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setFocusable(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Master.setBackground(new java.awt.Color(153, 153, 153));
        Master.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Master.setForeground(new java.awt.Color(153, 153, 153));
        Master.setText("MASTER DATA");

        Details_administrator.setBackground(new java.awt.Color(255, 255, 255));

        animate_show2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show2Layout = new javax.swing.GroupLayout(animate_show2);
        animate_show2.setLayout(animate_show2Layout);
        animate_show2Layout.setHorizontalGroup(
            animate_show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show2Layout.setVerticalGroup(
            animate_show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_detailsmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/admin.png"))); // NOI18N

        List_administrator.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        List_administrator.setText("Administrator VxkNET");
        List_administrator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_administratorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                List_administratorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                List_administratorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Details_administratorLayout = new javax.swing.GroupLayout(Details_administrator);
        Details_administrator.setLayout(Details_administratorLayout);
        Details_administratorLayout.setHorizontalGroup(
            Details_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_administratorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_detailsmember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(List_administrator, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Details_administratorLayout.setVerticalGroup(
            Details_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_administratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Details_administratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_detailsmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(List_administrator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        New_product.setBackground(new java.awt.Color(255, 255, 255));

        animate_show3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show3Layout = new javax.swing.GroupLayout(animate_show3);
        animate_show3.setLayout(animate_show3Layout);
        animate_show3Layout.setHorizontalGroup(
            animate_show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show3Layout.setVerticalGroup(
            animate_show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_detailsmember1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Add List.png"))); // NOI18N

        Add_product.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Add_product.setText("New Product");
        Add_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_productMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_productMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_productMouseExited(evt);
            }
        });

        javax.swing.GroupLayout New_productLayout = new javax.swing.GroupLayout(New_product);
        New_product.setLayout(New_productLayout);
        New_productLayout.setHorizontalGroup(
            New_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(New_productLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_detailsmember1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        New_productLayout.setVerticalGroup(
            New_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, New_productLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(New_productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_detailsmember1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Add_product, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TopupGame.setBackground(new java.awt.Color(255, 255, 255));

        animate_show4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show4Layout = new javax.swing.GroupLayout(animate_show4);
        animate_show4.setLayout(animate_show4Layout);
        animate_show4Layout.setHorizontalGroup(
            animate_show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show4Layout.setVerticalGroup(
            animate_show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_topupgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Game Controller.png"))); // NOI18N

        Topup_Game.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Topup_Game.setText("Top-Up Games");
        Topup_Game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Topup_GameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Topup_GameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Topup_GameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TopupGameLayout = new javax.swing.GroupLayout(TopupGame);
        TopupGame.setLayout(TopupGameLayout);
        TopupGameLayout.setHorizontalGroup(
            TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopupGameLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_topupgame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topup_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        TopupGameLayout.setVerticalGroup(
            TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopupGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_topupgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Topup_Game, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FoodandDrink.setBackground(new java.awt.Color(255, 255, 255));

        animate_show6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show6Layout = new javax.swing.GroupLayout(animate_show6);
        animate_show6.setLayout(animate_show6Layout);
        animate_show6Layout.setHorizontalGroup(
            animate_show6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show6Layout.setVerticalGroup(
            animate_show6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_topupgame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Restaurant Menu.png"))); // NOI18N

        Food_Drink.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Food_Drink.setText("Food and Drink");
        Food_Drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FoodandDrinkLayout = new javax.swing.GroupLayout(FoodandDrink);
        FoodandDrink.setLayout(FoodandDrinkLayout);
        FoodandDrinkLayout.setHorizontalGroup(
            FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodandDrinkLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_topupgame1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Food_Drink, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        FoodandDrinkLayout.setVerticalGroup(
            FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FoodandDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_topupgame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Food_Drink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Details_member.setBackground(new java.awt.Color(255, 255, 255));

        animate_show5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show5Layout = new javax.swing.GroupLayout(animate_show5);
        animate_show5.setLayout(animate_show5Layout);
        animate_show5Layout.setHorizontalGroup(
            animate_show5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show5Layout.setVerticalGroup(
            animate_show5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_detailsmember2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Checked Identification Documents.png"))); // NOI18N

        List_member.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        List_member.setText("List Member");
        List_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                List_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                List_memberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Details_memberLayout = new javax.swing.GroupLayout(Details_member);
        Details_member.setLayout(Details_memberLayout);
        Details_memberLayout.setHorizontalGroup(
            Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_memberLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_detailsmember2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(List_member, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Details_memberLayout.setVerticalGroup(
            Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_memberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_detailsmember2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(List_member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Transaction_History.setBackground(new java.awt.Color(255, 255, 255));

        animate_show9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show9Layout = new javax.swing.GroupLayout(animate_show9);
        animate_show9.setLayout(animate_show9Layout);
        animate_show9Layout.setHorizontalGroup(
            animate_show9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show9Layout.setVerticalGroup(
            animate_show9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_transactionhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Combo Chart.png"))); // NOI18N

        history.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        history.setText("Transaction History");
        history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Transaction_HistoryLayout = new javax.swing.GroupLayout(Transaction_History);
        Transaction_History.setLayout(Transaction_HistoryLayout);
        Transaction_HistoryLayout.setHorizontalGroup(
            Transaction_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Transaction_HistoryLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_transactionhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Transaction_HistoryLayout.setVerticalGroup(
            Transaction_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Transaction_HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Transaction_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_transactionhistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(history, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Billing_system3)
                .addGap(8, 8, 8)
                .addComponent(Billing_system1)
                .addGap(2, 2, 2)
                .addComponent(Billing_system2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Master)
                            .addGap(129, 129, 129))
                        .addComponent(Transaction_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Details_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FoodandDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TopupGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(New_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Details_administrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Billing_system1)
                            .addComponent(Billing_system2)))
                    .addComponent(Billing_system3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Master, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Details_administrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(New_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Details_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(TopupGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(FoodandDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Transaction_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        Alterlayer.add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 830));

        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setBackground(new java.awt.Color(27, 34, 45));

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1430, Short.MAX_VALUE)
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Right.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forshow.setBackground(new java.awt.Color(255, 255, 255));
        forshow.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout MainbarLayout = new javax.swing.GroupLayout(Mainbar);
        Mainbar.setLayout(MainbarLayout);
        MainbarLayout.setHorizontalGroup(
            MainbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainbarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(forshow, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MainbarLayout.setVerticalGroup(
            MainbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainbarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(forshow, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Right.add(Mainbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1230, 760));

        Alterlayer.add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1230, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alterlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alterlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Alterlayer.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void List_administratorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_administratorMouseClicked
        Details_administrator.setBackground(new Color(232,232,232));
        animate_show2.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new Administrator_List());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_List_administratorMouseClicked

    private void List_administratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_administratorMouseEntered
        // TODO add your handling code here:
        Details_administrator.setBackground(new Color(242,242,242));
        animate_show2.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_List_administratorMouseEntered

    private void List_administratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_administratorMouseExited
        // TODO add your handling code here:
        Details_administrator.setBackground(new Color(255,255,255));
        animate_show2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_List_administratorMouseExited

    private void Add_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_productMouseClicked
        New_product.setBackground(new Color(232,232,232));
        animate_show3.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new New_Product());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_Add_productMouseClicked

    private void Add_productMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_productMouseEntered
        New_product.setBackground(new Color(242,242,242));
        animate_show3.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Add_productMouseEntered

    private void Add_productMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_productMouseExited
        New_product.setBackground(new Color(255,255,255));
        animate_show3.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Add_productMouseExited

    private void Topup_GameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseClicked
        TopupGame.setBackground(new Color(232,232,232));
        animate_show4.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new History_Transaction_Topupgame());
        forshow.repaint();
        forshow.revalidate();
        
    }//GEN-LAST:event_Topup_GameMouseClicked

    private void Topup_GameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseEntered
        TopupGame.setBackground(new Color(242,242,242));
        animate_show4.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Topup_GameMouseEntered

    private void Topup_GameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseExited
        TopupGame.setBackground(new Color(255,255,255));
        animate_show4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Topup_GameMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        
            int jawab = JOptionPane.showConfirmDialog(null, "Anda ingin melakukan Logout, lanjutkan ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(jawab == 0){
                System.out.println("Sip balik ke login page");
                    Login LoginFrame = new Login();
                    LoginFrame.pack();
                    LoginFrame.setLocationRelativeTo(null); 
                    LoginFrame.setVisible(true);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            dispose();
                        }
                    });
            }else{
                System.out.println("tetap disini");
            }
    }//GEN-LAST:event_LogoutActionPerformed

    private void Food_DrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseClicked
        FoodandDrink.setBackground(new Color(232,232,232));
        animate_show6.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new FoodandDrink());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_Food_DrinkMouseClicked

    private void Food_DrinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseEntered
        FoodandDrink.setBackground(new Color(242,242,242));
        animate_show6.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Food_DrinkMouseEntered

    private void Food_DrinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseExited
        FoodandDrink.setBackground(new Color(255,255,255));
        animate_show6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Food_DrinkMouseExited

    private void List_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseClicked
        Details_member.setBackground(new Color(232,232,232));
        animate_show5.setBackground(new Color(27,34,45));

        forshow.removeAll();
        forshow.add(new Member_List_ownerdash());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_List_memberMouseClicked

    private void List_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseEntered
        // TODO add your handling code here:
        Details_member.setBackground(new Color(242,242,242));
        animate_show5.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_List_memberMouseEntered

    private void List_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseExited
        // TODO add your handling code here:
        Details_member.setBackground(new Color(255,255,255));
        animate_show5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_List_memberMouseExited

    private void historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseClicked
        Transaction_History.setBackground(new Color(232,232,232));
        animate_show9.setBackground(new Color(27,34,45));

        forshow.removeAll();
        forshow.add(new History_Transaction());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_historyMouseClicked

    private void historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseEntered
        Transaction_History.setBackground(new Color(242,242,242));
        animate_show9.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_historyMouseEntered

    private void historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historyMouseExited
        Transaction_History.setBackground(new Color(255,255,255));
        animate_show9.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_historyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboardowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboardowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboardowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboardowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboardowner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_product;
    private javax.swing.JPanel Alterlayer;
    private javax.swing.JLabel Billing_system1;
    private javax.swing.JLabel Billing_system2;
    private javax.swing.JLabel Billing_system3;
    private javax.swing.JPanel Details_administrator;
    private javax.swing.JPanel Details_member;
    private javax.swing.JLabel Food_Drink;
    private javax.swing.JPanel FoodandDrink;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel List_administrator;
    private javax.swing.JLabel List_member;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel Mainbar;
    private javax.swing.JLabel Master;
    private javax.swing.JPanel Navbar;
    private javax.swing.JPanel New_product;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel TopupGame;
    private javax.swing.JLabel Topup_Game;
    private javax.swing.JPanel Transaction_History;
    private javax.swing.JPanel animate_show2;
    private javax.swing.JPanel animate_show3;
    private javax.swing.JPanel animate_show4;
    private javax.swing.JPanel animate_show5;
    private javax.swing.JPanel animate_show6;
    private javax.swing.JPanel animate_show9;
    private javax.swing.JPanel forshow;
    private javax.swing.JLabel history;
    private javax.swing.JLabel icon_detailsmember;
    private javax.swing.JLabel icon_detailsmember1;
    private javax.swing.JLabel icon_detailsmember2;
    private javax.swing.JLabel icon_topupgame;
    private javax.swing.JLabel icon_topupgame1;
    private javax.swing.JLabel icon_transactionhistory;
    // End of variables declaration//GEN-END:variables
}
