/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BillingManagementSys;

import Aio.BillingSystem;
import Aio.Find_Member;
import Aio.FoodandDrink;
import Aio.FoodandDrink_List;
import Aio.Member_List;
import Aio.New_Member;
import Aio.New_Product;
import Aio.TopupGameList;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Fancysx
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alterlayer = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Billing_system1 = new javax.swing.JLabel();
        Billing_system2 = new javax.swing.JLabel();
        Billing_system3 = new javax.swing.JLabel();
        Member = new javax.swing.JLabel();
        add_member = new javax.swing.JPanel();
        animate_show = new javax.swing.JPanel();
        icon_newmember = new javax.swing.JLabel();
        new_member = new javax.swing.JLabel();
        Details_member = new javax.swing.JPanel();
        animate_show2 = new javax.swing.JPanel();
        icon_detailsmember = new javax.swing.JLabel();
        List_member = new javax.swing.JLabel();
        Product = new javax.swing.JLabel();
        Find_member = new javax.swing.JPanel();
        animate_show5 = new javax.swing.JPanel();
        icon_Findmember = new javax.swing.JLabel();
        get_memberdata = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        TopupGame = new javax.swing.JPanel();
        animate_show4 = new javax.swing.JPanel();
        icon_topupgame = new javax.swing.JLabel();
        Topup_Game = new javax.swing.JLabel();
        FoodandDrink = new javax.swing.JPanel();
        animate_show6 = new javax.swing.JPanel();
        icon_topupgame1 = new javax.swing.JLabel();
        Food_Drink = new javax.swing.JLabel();
        Product1 = new javax.swing.JLabel();
        Billing = new javax.swing.JPanel();
        animate_show7 = new javax.swing.JPanel();
        icon_billing = new javax.swing.JLabel();
        Billing_system = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Navbar = new javax.swing.JPanel();
        Mainbar = new javax.swing.JPanel();
        forshow = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Alterlayer.setBackground(new java.awt.Color(251, 251, 251));
        Alterlayer.setName(""); // NOI18N
        Alterlayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Left.setBackground(new java.awt.Color(255, 255, 255));

        Billing_system1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Billing_system1.setText("VxK");

        Billing_system2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Billing_system2.setText("NET™");

        Billing_system3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Billing_system3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Battle.net.png"))); // NOI18N

        Member.setBackground(new java.awt.Color(153, 153, 153));
        Member.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Member.setForeground(new java.awt.Color(153, 153, 153));
        Member.setText("MEMBER");

        add_member.setBackground(new java.awt.Color(255, 255, 255));

        animate_show.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_showLayout = new javax.swing.GroupLayout(animate_show);
        animate_show.setLayout(animate_showLayout);
        animate_showLayout.setHorizontalGroup(
            animate_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_showLayout.setVerticalGroup(
            animate_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_newmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Add Male User Group.png"))); // NOI18N

        new_member.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        new_member.setText("New Member");
        new_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_memberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout add_memberLayout = new javax.swing.GroupLayout(add_member);
        add_member.setLayout(add_memberLayout);
        add_memberLayout.setHorizontalGroup(
            add_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_memberLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_newmember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(new_member, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        add_memberLayout.setVerticalGroup(
            add_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_memberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_newmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_member, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Details_member.setBackground(new java.awt.Color(255, 255, 255));

        animate_show2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show2Layout = new javax.swing.GroupLayout(animate_show2);
        animate_show2.setLayout(animate_show2Layout);
        animate_show2Layout.setHorizontalGroup(
            animate_show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show2Layout.setVerticalGroup(
            animate_show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_detailsmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Checked Identification Documents.png"))); // NOI18N

        List_member.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        List_member.setText("List Member");
        List_member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List_memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                List_memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                List_memberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Details_memberLayout = new javax.swing.GroupLayout(Details_member);
        Details_member.setLayout(Details_memberLayout);
        Details_memberLayout.setHorizontalGroup(
            Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_memberLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_detailsmember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(List_member, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Details_memberLayout.setVerticalGroup(
            Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_memberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Details_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_detailsmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(List_member, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Product.setBackground(new java.awt.Color(153, 153, 153));
        Product.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Product.setForeground(new java.awt.Color(153, 153, 153));
        Product.setText("PRODUCT");

        Find_member.setBackground(new java.awt.Color(255, 255, 255));

        animate_show5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show5Layout = new javax.swing.GroupLayout(animate_show5);
        animate_show5.setLayout(animate_show5Layout);
        animate_show5Layout.setHorizontalGroup(
            animate_show5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show5Layout.setVerticalGroup(
            animate_show5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_Findmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Facial Recognition.png"))); // NOI18N

        get_memberdata.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        get_memberdata.setText("Find Member");
        get_memberdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_memberdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                get_memberdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                get_memberdataMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Find_memberLayout = new javax.swing.GroupLayout(Find_member);
        Find_member.setLayout(Find_memberLayout);
        Find_memberLayout.setHorizontalGroup(
            Find_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Find_memberLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_Findmember, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(get_memberdata, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Find_memberLayout.setVerticalGroup(
            Find_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Find_memberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Find_memberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_Findmember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(get_memberdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Logout.setBackground(new java.awt.Color(27, 34, 45));
        Logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setFocusable(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        TopupGame.setBackground(new java.awt.Color(255, 255, 255));

        animate_show4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show4Layout = new javax.swing.GroupLayout(animate_show4);
        animate_show4.setLayout(animate_show4Layout);
        animate_show4Layout.setHorizontalGroup(
            animate_show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show4Layout.setVerticalGroup(
            animate_show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_topupgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Game Controller.png"))); // NOI18N

        Topup_Game.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Topup_Game.setText("Top-Up Games");
        Topup_Game.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Topup_GameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Topup_GameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Topup_GameMouseExited(evt);
            }
        });

        javax.swing.GroupLayout TopupGameLayout = new javax.swing.GroupLayout(TopupGame);
        TopupGame.setLayout(TopupGameLayout);
        TopupGameLayout.setHorizontalGroup(
            TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopupGameLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_topupgame, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Topup_Game, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        TopupGameLayout.setVerticalGroup(
            TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopupGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopupGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_topupgame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Topup_Game, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FoodandDrink.setBackground(new java.awt.Color(255, 255, 255));

        animate_show6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show6Layout = new javax.swing.GroupLayout(animate_show6);
        animate_show6.setLayout(animate_show6Layout);
        animate_show6Layout.setHorizontalGroup(
            animate_show6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show6Layout.setVerticalGroup(
            animate_show6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_topupgame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Restaurant Menu.png"))); // NOI18N

        Food_Drink.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Food_Drink.setText("Food and Drink");
        Food_Drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Food_DrinkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout FoodandDrinkLayout = new javax.swing.GroupLayout(FoodandDrink);
        FoodandDrink.setLayout(FoodandDrinkLayout);
        FoodandDrinkLayout.setHorizontalGroup(
            FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoodandDrinkLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_topupgame1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Food_Drink, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        FoodandDrinkLayout.setVerticalGroup(
            FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FoodandDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoodandDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_topupgame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Food_Drink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Product1.setBackground(new java.awt.Color(153, 153, 153));
        Product1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Product1.setForeground(new java.awt.Color(153, 153, 153));
        Product1.setText("Billing ");

        Billing.setBackground(new java.awt.Color(255, 255, 255));

        animate_show7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout animate_show7Layout = new javax.swing.GroupLayout(animate_show7);
        animate_show7.setLayout(animate_show7Layout);
        animate_show7Layout.setHorizontalGroup(
            animate_show7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        animate_show7Layout.setVerticalGroup(
            animate_show7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        icon_billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Src/Online Payment with a Credit Card.png"))); // NOI18N

        Billing_system.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Billing_system.setText("Billing System");
        Billing_system.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Billing_systemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Billing_systemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Billing_systemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BillingLayout = new javax.swing.GroupLayout(Billing);
        Billing.setLayout(BillingLayout);
        BillingLayout.setHorizontalGroup(
            BillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillingLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(animate_show7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon_billing, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Billing_system, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        BillingLayout.setVerticalGroup(
            BillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon_billing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animate_show7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Billing_system, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Details_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Find_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Member, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FoodandDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LeftLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TopupGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Product1)))
                .addGap(0, 28, Short.MAX_VALUE))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Billing_system3)
                .addGap(8, 8, 8)
                .addComponent(Billing_system1)
                .addGap(2, 2, 2)
                .addComponent(Billing_system2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Billing_system3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Billing_system1)
                            .addComponent(Billing_system2))
                        .addGap(17, 17, 17)))
                .addGap(14, 14, 14)
                .addComponent(Member, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(add_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Details_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Find_member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Product)
                .addGap(8, 8, 8)
                .addComponent(TopupGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(FoodandDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Product1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Billing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        Alterlayer.add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 830));

        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setBackground(new java.awt.Color(27, 34, 45));

        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1430, Short.MAX_VALUE)
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Right.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forshow.setBackground(new java.awt.Color(255, 255, 255));
        forshow.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout MainbarLayout = new javax.swing.GroupLayout(Mainbar);
        Mainbar.setLayout(MainbarLayout);
        MainbarLayout.setHorizontalGroup(
            MainbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainbarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(forshow, javax.swing.GroupLayout.PREFERRED_SIZE, 1185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MainbarLayout.setVerticalGroup(
            MainbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainbarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(forshow, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Right.add(Mainbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1230, 760));

        Alterlayer.add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1230, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alterlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alterlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Alterlayer.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void List_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseClicked
        Details_member.setBackground(new Color(232,232,232));
        animate_show2.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new Member_List());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_List_memberMouseClicked

    private void List_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseEntered
        // TODO add your handling code here:
        Details_member.setBackground(new Color(242,242,242));
        animate_show2.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_List_memberMouseEntered

    private void List_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_memberMouseExited
        // TODO add your handling code here:
        Details_member.setBackground(new Color(255,255,255));
        animate_show2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_List_memberMouseExited

    private void Topup_GameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseClicked
        TopupGame.setBackground(new Color(232,232,232));
        animate_show4.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new TopupGameList());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_Topup_GameMouseClicked

    private void Topup_GameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseEntered
        TopupGame.setBackground(new Color(242,242,242));
        animate_show4.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Topup_GameMouseEntered

    private void Topup_GameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Topup_GameMouseExited
        TopupGame.setBackground(new Color(255,255,255));
        animate_show4.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Topup_GameMouseExited

    private void get_memberdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_memberdataMouseClicked
        Find_member.setBackground(new Color(232,232,232));
        animate_show5.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new Find_Member());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_get_memberdataMouseClicked

    private void get_memberdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_memberdataMouseEntered
        Find_member.setBackground(new Color(242,242,242));
        animate_show5.setBackground(new Color(27,34,45));
      
    }//GEN-LAST:event_get_memberdataMouseEntered

    private void get_memberdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_memberdataMouseExited
        Find_member.setBackground(new Color(255,255,255));
        animate_show5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_get_memberdataMouseExited

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        
            int jawab = JOptionPane.showConfirmDialog(null, "Anda ingin melakukan Logout, lanjutkan ?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if(jawab == 0){
                System.out.println("Sip balik ke login page");
                    Login LoginFrame = new Login();
                    LoginFrame.pack();
                    LoginFrame.setLocationRelativeTo(null); 
                    LoginFrame.setVisible(true);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            dispose();
                        }
                    });
            }else{
                System.out.println("tetap disini");
            }
    }//GEN-LAST:event_LogoutActionPerformed

    private void Food_DrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseClicked
        FoodandDrink.setBackground(new Color(232,232,232));
        animate_show6.setBackground(new Color(27,34,45));
        
        forshow.removeAll();
        forshow.add(new FoodandDrink_List());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_Food_DrinkMouseClicked

    private void Food_DrinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseEntered
        FoodandDrink.setBackground(new Color(242,242,242));
        animate_show6.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Food_DrinkMouseEntered

    private void Food_DrinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Food_DrinkMouseExited
        FoodandDrink.setBackground(new Color(255,255,255));
        animate_show6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Food_DrinkMouseExited

    private void new_memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_memberMouseExited
        add_member.setBackground(new Color(255,255,255));
        animate_show.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_new_memberMouseExited

    private void new_memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_memberMouseEntered
        add_member.setBackground(new Color(242,242,242));
        animate_show.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_new_memberMouseEntered

    private void new_memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_memberMouseClicked
        add_member.setBackground(new Color(232,232,232));
        animate_show.setBackground(new Color(27,34,45));

        forshow.removeAll();
        forshow.add(new New_Member());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_new_memberMouseClicked

    private void Billing_systemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Billing_systemMouseClicked
        Billing.setBackground(new Color(232,232,232));
        animate_show7.setBackground(new Color(27,34,45));

        forshow.removeAll();
        forshow.add(new BillingSystem());
        forshow.repaint();
        forshow.revalidate();
    }//GEN-LAST:event_Billing_systemMouseClicked

    private void Billing_systemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Billing_systemMouseEntered
        Billing.setBackground(new Color(242,242,242));
        animate_show7.setBackground(new Color(27,34,45));
    }//GEN-LAST:event_Billing_systemMouseEntered

    private void Billing_systemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Billing_systemMouseExited
        Billing.setBackground(new Color(255,255,255));
        animate_show7.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Billing_systemMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alterlayer;
    private javax.swing.JPanel Billing;
    private javax.swing.JLabel Billing_system;
    private javax.swing.JLabel Billing_system1;
    private javax.swing.JLabel Billing_system2;
    private javax.swing.JLabel Billing_system3;
    private javax.swing.JPanel Details_member;
    private javax.swing.JPanel Find_member;
    private javax.swing.JLabel Food_Drink;
    private javax.swing.JPanel FoodandDrink;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel List_member;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel Mainbar;
    private javax.swing.JLabel Member;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel Product;
    private javax.swing.JLabel Product1;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel TopupGame;
    private javax.swing.JLabel Topup_Game;
    private javax.swing.JPanel add_member;
    private javax.swing.JPanel animate_show;
    private javax.swing.JPanel animate_show2;
    private javax.swing.JPanel animate_show4;
    private javax.swing.JPanel animate_show5;
    private javax.swing.JPanel animate_show6;
    private javax.swing.JPanel animate_show7;
    private javax.swing.JPanel forshow;
    private javax.swing.JLabel get_memberdata;
    private javax.swing.JLabel icon_Findmember;
    private javax.swing.JLabel icon_billing;
    private javax.swing.JLabel icon_detailsmember;
    private javax.swing.JLabel icon_newmember;
    private javax.swing.JLabel icon_topupgame;
    private javax.swing.JLabel icon_topupgame1;
    private javax.swing.JLabel new_member;
    // End of variables declaration//GEN-END:variables
}
